# Generated by Django 4.2.4 on 2023-09-13 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
