# Generated by Django 4.2.4 on 2023-09-16 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fpr', '0003_reservation_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='hotel',
        ),
    ]
