# Generated by Django 4.2.4 on 2023-09-17 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fpr', '0004_remove_reservation_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fpr.hotel'),
            preserve_default=False,
        ),
    ]
