# Generated by Django 4.2.4 on 2023-09-17 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fpr', '0005_reservation_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='hotel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fpr.hotel'),
        ),
    ]
