# Generated by Django 4.2.5 on 2023-09-19 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fpr', '0007_alter_roomtype_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='fpr.hotel'),
        ),
    ]
